version: '3.8'

services:
  llmmux:
    image: llmmux:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - API_KEYS=your-secret-key-1,your-secret-key-2
      # Option 1: Manual backend configuration
      - BACKENDS=model-name:host:port,another-model:host:port
      # Option 2: Auto-discovery (recommended)
      # - VLLM_SERVERS=vllm-server-1:8000,vllm-server-2:8001
      - ENABLE_CORS=true
      - CORS_ORIGIN=*
      - HEALTH_CHECK_INTERVAL=30000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - vllm-server-1
      - vllm-server-2

  # Example vLLM servers (uncomment and configure as needed)
  # vllm-server-1:
  #   image: vllm/vllm-openai:latest
  #   ports:
  #     - "8000:8000"
  #   command: ["--model", "microsoft/DialoGPT-medium", "--host", "0.0.0.0", "--port", "8000"]
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # vllm-server-2:
  #   image: vllm/vllm-openai:latest
  #   ports:
  #     - "8001:8001"
  #   command: ["--model", "gpt2", "--host", "0.0.0.0", "--port", "8001"]
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8001/v1/models"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
